### ISSUE TITLE
Embedded lyrics not shown unless 'Download lyrics automatically' is checked

### ISSUE THREAD

**Issue by madrats** [digimezzo/dopamine-windows#208] opened 2016-11-24 02:33 UTC
As it says in the title. 
Most of my songs have lyrics embedded and those that don't can't be found online anyway. So this causes unnecessary searching for those few songs. Logically, these should not be linked to one another.

**Comment by digimezzo** [comment] 2016-11-24 06:22
That's a bug, caused by a misplaced piece of code :) It'll be fixed in the next preview.

**Closed as completed** 2016-11-24 06:23 UTC
Labels: bug
