### ISSUE TITLE
Window resizes behind start bar again

### ISSUE THREAD

**Issue by 1suky1** [digimezzo/dopamine-windows#465] opened 2017-07-26 07:50 UTC
Dopamine window is resizing behind start bar again with the latest version (1.3 build 927).
 
When I close or minimise the window and bring it back up from taskbar icon it expands behind the start bar. Also, when I bring back the window from a pinned start bar icon it expands on top outside my desktop boundaries.

**Comment by Magentaize** [comment] 2017-07-26 15:09
Are you using a top taskbar?

**Comment by 1suky1** [comment] 2017-07-26 15:21
No, the taskbar is at the bottom. This was an issue before and was fixed but now it's back.

**Comment by Magentaize** [comment] 2017-07-26 15:50
Sorry, I cannot reproduce here. Can you make a clean re-installing and try again?

**Comment by 1suky1** [comment] 2017-07-26 17:23
Just reinstalled, same thing.

While dopamine is maximized you minimize/close it to taskbar tray bar (the
bottom right thingy in start bar, have no idea what it's called these days)
Then open it from the taskbar tray icon in the bottom right by double
clicking on the icon
And it will be maximized behind the start bar.

If I right click-> show dopamine it brings it back fine.

If I have dopamine pinned on start bar, when I click on it to open it the
window is placed above start bar but is expanding beyond the top part of
the desktop.

**Comment by Magentaize** [comment] 2017-07-27 14:02
Now I got it, and it will be fixed in next version.

**Closed as completed** 2017-07-29 13:00 UTC
