### ISSUE TITLE
Artists/Genres left panel #-Z cut off

### ISSUE THREAD

**Issue by The-Choo-Choo-Shoe** [digimezzo/dopamine-windows#919] opened 2018-12-02 04:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression 
[ X ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 1809
* Dopamine version: 2.0 Preview 5

## Reproduction steps

* Step 1: Select Artists or Genres tab.
* Step 2: Set a small sized left panel.
* Step 3: In the left panel click any of the #-Z buttons in the list.

## Observed behavior

It shows a #-Z list of your artists/genres with selectable characters to quickly jump to that section of the library, the right side of the list is cut off.
## Desired behavior

If the left panel is set to the minimum width it would be preferable if the selectable buttons for #-Z would squeeze together so the right part is not cut off.

**Comment by The-Choo-Choo-Shoe** [comment] 2018-12-02 04:05
![untitled 2](https://user-images.githubusercontent.com/31801661/49335567-d38ca980-f5ef-11e8-839f-636cf112533b.png)

**Comment by digimezzo** [comment] 2018-12-02 07:11
Duplicate of #790. I'm cloosing this issue in favor of the other one.

**Comment by The-Choo-Choo-Shoe** [comment] 2018-12-02 09:14
Sorry, I did my best to search for this issue before posting and couldn't find it.

**Closed as completed** 2018-12-21 17:10 UTC
