### ISSUE TITLE
Media key doesn't work with windows 10 notification.

### ISSUE THREAD

**Issue by Zhails** [digimezzo/dopamine-windows#566] opened 2017-11-21 07:31 UTC
This bug previously was in beta versions, in stable it hasn't been fixed too.

**Comment by digimezzo** [comment] 2017-11-21 14:35
Is this related to #524 or is it something else? Could you specify what you are trying to do? I'm asking because last time I tested, pressing media keys did pop up the system notification.

**Comment by Zhails** [comment] 2017-11-21 15:02
Not the same. When I use windows notifications and want to pause/play etc via touchpad gestures (in general it is the same as media keys) nothing happens, even notification doesn't appears. If I open notification via volume up, I can't pause/play etc pressing notification buttons. There is animation in the last case, but no action. Windows 10 x64 17040

**Comment by digimezzo** [comment] 2017-11-21 22:16
I can't reproduce the issue with the trackpad gestures (I don't have gestures here). The keyboard media keys trigger the notification, button pressing the buttons on the notification indeed is broken. It was broken by fd18b56759217992e52aa9a9dcad0be45ee38f62.
We'll have to re-add SMCButtonPressed, and make sure that it doesn't interfere with listening to media keys from within the shell.

**Comment by digimezzo** [comment] 2017-11-22 06:44
Buttons not working is fixed in 1c8d52782dbb0a85f42d413957608b4a12584a74 I'm not sure if that also fixes trackpad gestures. Please check it when Dopamine 1.5.3 is released.

**Comment by Zhails** [comment] 2017-11-23 20:29
Yes, it fixed. Thank you.

**Comment by digimezzo** [comment] 2017-11-23 23:03
Thanks for confirming. I'm closing this issue.

**Closed as completed by digimezzo** 2017-11-23 23:03 UTC
Labels: bug
