### ISSUE TITLE
Change sound icon

### ISSUE THREAD

**Issue by kukata-81** [digimezzo/dopamine-windows#949] opened 2019-01-26 10:42 UTC
If the icon can be made progressive.
![opera _2019-01-26_124142_www neowin net](https://user-images.githubusercontent.com/47054924/51786054-ca3f3980-2167-11e9-873a-5c682986425f.png)

**Comment by digimezzo** [comment] 2019-03-10 14:27
Duplicate of #501

**Comment by digimezzo** [comment] 2021-03-04 14:55
This is implemented in Dopamine 3.0.

**Closed as completed** 2021-03-04 14:56 UTC
Labels: enhancement
